### PR TITLE
Fix handling of multiple rodisk inputs

### PR DESCRIPTION
**Pull request by Marlin-Na**
Fix bug that when multiple "rodisk://" inputs are supplied, only the last disk will be mounted.

### CODE REVIEW

**Comment by julianhess** [comment]
I'm going to hold off merging this as-is, since it's a hack around my original bug. Let's actually fix this properly, and create this as a colon delimited list as you suggest:

https://github.com/getzlab/canine/blob/29d7acaa2bc407e3af7b97ca6131527e39d56545/canine/localization/base.py#L671

or perhaps export multiple variables.

**Comment by Marlin-Na** [comment]
I agree. Actually multiple variables probably be cleaner. How do you think about adding `CANINE_LOCAL_DISK_DIR_1`, `CANINE_LOCAL_DISK_DIR_2`... to exports and referencing them in localization script? If you are okay, I am going to make a commit.

**Comment by julianhess** [comment]
That's exactly what I was thinking!

**Comment by julianhess** [comment]
Just rebased onto the latest Canine `master` (ae280ee)

**Pull request merged**
