### PR TITLE
Use delayed localization by default for gs:// files

### PR DESCRIPTION
**Pull request by julianhess**
Localizing everything on the controller by default will quickly bottleneck, and there's zero downside to handling localization on the worker node by default.

### CODE REVIEW

**Comment by Marlin-Na** [comment]
In case of a scatter task with delayed localization, will the file be downloaded multiple times on every worker node?

**Comment by julianhess** [comment]
I think that should be identified beforehand as a common input?

**Comment by Marlin-Na** [comment]
But how a common input localization can be delayed to multiple worker nodes?

**Comment by julianhess** [comment]
It won't be. Common inputs will still be handled on the controller node, and can still potentially cause bottlenecks.

**Comment by Marlin-Na** [comment]
Cool!

**Comment by julianhess** [comment]
Instead of falling back to handling it like a local file, we should fall back to the inferred behavior for the input.

https://github.com/getzlab/canine/blob/fcb80bbbe32329fd20b1fcbe9a47de237bdfba0e/canine/localization/base.py#L580-L586

If someone erroneously specifies that a `rodisk://` input should be `delayed`, it won't get handled properly.

**Pull request merged**
